#!/usr/bin/env python3

import rospy

# we are sending Int32 message
from std_msgs.msg import Int32

#this the node name
nodeName='messagesubs'

#these are the topic names
#these topic names have to match the topic names specified in the Arduino code
topicNameLeftEncoder='left_encoder_pulses'
topicNameRightEncoder='right_encoder_pulses'

#These are the call back functions, that are called when the messages are received
#These functions will print the encoder readings to the screen

def callBackFunctionLeftEncoder(message1):
    print("Left encoder pulses: %s" message1.data)

def callBackFunctionRightEncoder(message2):
    print("right encoder pulses: %s" message2.data)

# here, we initialize our subscriber node
#we set "anonymous=True" to make sure that the node has a unique name # this parameter will add random numbers to the end of the node name

rospy.init_node(nodeName, anonymous=True)

# here, we subscribe to the appropriate topics
#we specify the type of the message we want to receive # and we specify the call back functions

rospy.Subscriber(topicNameLeftEncoder, Int32, callBackFunctionLeftEncoder)
rospy.Subscriber(topicNameRightEncoder, Int32, callBackFunctionRightEncoder)

# spin the code
rospy.spin()